baseURL = "https://naturopathie.netlify.app"
languageCode = "fr-FR"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "Happy Naturo pattes"
[[menu.main]]
URL = "categories/tarif/"
name = "tarif"
weight = ""
[[menu.main]]
URL = "categories/prestation/"
name = "prestations"
weight = ""
[[menu.main]]
URL = "about"
name = "À propos"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "72, Le Village\n35190 La Chapelle au Filtzméens"
author = "Catherine Namèche"
author_image = "images/banner-img.png"
bio = "La naturopathie - L’Homme - L’Animal\nPrenez votre santé et celle de vos animaux domestiques en main."
contact_form_action = "mailto:happynaturopattes@gmail.com"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "La naturopathie - L’Homme - L’Animal\nPrenez votre santé et celle de vos animaux domestiques en main."
email = "happynaturopattes@gmail.com"
google_analitycs_id = "Your ID"
home = "Accueil"
layout = "1"
logo = "images/logo.png"
logoDesc = "images/logo-desc.png"
mobile = "0781667339"
preloader = true
search = true
social = []
[params.instafeed]
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = false
user_id = "4044026246"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
